<?php

namespace megaoffice\client;

class Component extends \yii\base\Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function test() {
        $a = 5;
    }
}